Repository nuclear-gandhi-team/betabid-front, pull requests merged in 2024-02, with the labels that each got.

#16 feature: add betModal
  package.json
  src/app/layout.tsx
  src/components/modules/bet-modal.tsx
  src/components/ui/dialog.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/sonner.tsx
  yarn.lock
Labels: enhancement

#18 feature: add actionsPage
  package.json
  src/app/(main)/browse/page.tsx
  src/app/(main)/layout.tsx
  src/app/(main)/lots/[lotId]/actions.tsx
  src/app/(main)/lots/[lotId]/overview.tsx
  src/app/(main)/lots/[lotId]/page.tsx
  src/app/(main)/my-lots/page.tsx
  src/app/(main)/saved/page.tsx
  src/components/modules/bet-modal.tsx
  src/components/modules/lot-action-card.tsx
  src/components/modules/lot-title.tsx
  src/components/modules/rate-changes-graph.tsx
  src/components/modules/rate-history/rate-hirstory-list.tsx
  src/components/modules/rate-history/rate-history.tsx
  src/components/ui/card.tsx
  src/components/ui/carousel.tsx
  src/components/ui/scroll-area.tsx
  src/components/ui/tabs.tsx
  src/lib/const/graph-data.ts
  src/lib/const/navigation-links.ts
  yarn.lock
Labels: enhancement

#21 feature: auth
  src/components/modules/auth/auth-modal.tsx
  src/components/modules/auth/login.tsx
  src/components/modules/auth/registration.tsx
Labels: enhancement

#22 fix: change styles
  src/components/modules/auth/auth-modal.tsx
  src/components/modules/auth/login.tsx
  src/components/modules/auth/registration.tsx
Labels: enhancement

#24 fix: password visibility
  src/components/modules/auth/registration.tsx
Labels: bug

#25 feature: browse page
  package.json
  src/app/(main)/browse/page.tsx
  src/components/modules/filters/filter.tsx
  src/components/modules/filters/toolbar.tsx
  src/components/modules/lot-card/star.tsx
  src/components/modules/page-title.tsx
  src/components/ui/command.tsx
  src/components/ui/pagination.tsx
  src/components/ui/popover.tsx
  yarn.lock
Labels: enhancement

#26 feature: added my lots page
  src/app/(main)/my-lots/page.tsx
Labels: enhancement

#27 feature: added saved page
  src/app/(main)/saved/page.tsx
Labels: enhancement

#28 feature: added settings page
  src/app/(main)/settings/page.tsx
Labels: enhancement

#40 feature: implemented loader for cards
  src/app/(main)/browse/page.tsx
  src/components/modules/card-skeleton.tsx
  src/components/ui/skeleton.tsx
Labels: enhancement

#42 feat: add example of api routes and connect with api
  .gitignore
  next.config.mjs
  package.json
  src/api/axios-wrapper.ts
  src/api/hooks/query/useGetAllLots.ts
  src/api/services/lots.ts
  src/api/types/lot.ts
  src/app/(main)/browse/page.tsx
  src/app/layout.tsx
  src/lib/provider.tsx
  yarn.lock
Labels: routes

#43 fix: settings page
  package.json
  src/app/(main)/settings/page.tsx
  src/components/ui/alert-dialog.tsx
  yarn.lock
Labels: enhancement

#44 feature: not found page
  src/app/(main)/saved/page.tsx
  src/components/modules/not-found.tsx
Labels: enhancement

#46 fix: skeleton module
  src/app/(main)/browse/page.tsx
  src/components/modules/skeletons/skeleton-card.tsx
  src/components/modules/skeletons/skeleton-filters.tsx
  src/components/modules/skeletons/skeleton-page.tsx
  src/components/modules/skeletons/skeleton-title.tsx
Labels: enhancement

#47 feature: added connect with api for login and registration
  package.json
  src/api/axios-wrapper.ts
  src/api/hooks/mutation/useLoginMutation.ts
  src/api/hooks/mutation/useRegisterMutation.ts
  src/api/hooks/query/useAllLotsQuery.ts
  src/api/services/user.ts
  src/api/types/all-lot.ts
  src/api/types/bid-history.ts
  src/api/types/login-credentials.ts
  src/api/types/lot.ts
  src/api/types/registration-credentials.ts
  src/app/(main)/browse/page.tsx
  src/app/(main)/layout.tsx
  src/app/(main)/lots/create/page.tsx
  src/app/auth/layout.tsx
  src/app/auth/login/page.tsx
  src/app/auth/register/page.tsx
  src/components/modules/auth/auth-modal.tsx
  src/components/ui/input.tsx
  yarn.lock
Labels: enhancement

#49 routes: create lot
  src/api/axios-wrapper.ts
  src/api/hooks/mutation/useCreateLotMutation.ts
  src/api/hooks/query/useStatusesQuery.ts
  src/api/hooks/query/useTagsQuery.ts
  src/api/services/lots.ts
  src/api/types/create-lot.ts
  src/app/(main)/lots/create/page.tsx
Labels: routes

#51 route: api filters
  src/api/hooks/query/useAllLotsQuery.ts
  src/api/services/lots.ts
  src/api/types/lot.ts
  src/app/(main)/browse/page.tsx
  src/app/(main)/my-lots/page.tsx
  src/components/modules/filters/filter.tsx
  src/components/modules/filters/toolbar.tsx
  src/components/modules/lot-card/lot-card.tsx
  src/components/modules/lot-card/status.tsx
  src/lib/utils.ts
Labels: enhancement

#54 fix: dev
  .idea/inspectionProfiles/Project_Default.xml
  src/app/(main)/browse/page.tsx
  src/components/modules/filters/toolbar.tsx
Labels: bug
